### ISSUE TITLE
use unittest.mock as a fallback

### ISSUE THREAD

**Issue by pgajdos** [googleapis/google-auth-library-python-httplib2#68]
Could you please consider to use unittest.mock instead of mock as a fallback? It looks like to work well at least for python 3.8+.

**Comment by pgajdos** [comment]
Background:
https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by clundin25** [comment]
Resolved by https://github.com/googleapis/google-auth-library-python-httplib2/pull/124
